
(function(compId){"use strict";var _=null,y=true,n=false,x2='5.0.0.375',x13='nowrap',x7='62',x1='5.0.0',p='px',x3='rgba(0,0,0,0)',x23='rgba(255,255,255,1)',g='image',x21='500',x12='700',l='normal',xc='rgba(0,0,0,1)',x17='none solid rgb(0, 0, 0)',x11='55',x='text',x8='advent-pro, sans-serif',x9='break-word',m='rect',x5='rgba(255,255,255,1.00)',x16='300',h='height',x15='21',i='none';var g4='Ideal-landscape.jpg';var s18="min:",s22="25°",s10="30°",s19="max:",s6="Locatie",s14="Voorspelling",s20="53°";var im='images/',aud='media/',vid='media/',js='js/',fonts={'advent-pro, sans-serif':'<script src=\"http://use.edgefonts.net/advent-pro:n2,n5,n7,n4,n1,n6,n3:all.js\"></script>'},opts={'gAudioPreloadPreference':'auto','gVideoPreloadPreference':'auto'},resources=[],scripts=["edge_includes/jquery-2.1.1.min.js"],symbols={"stage":{v:x1,mv:x1,b:x2,stf:h,cg:i,rI:n,cn:{dom:[{id:'Ideal-landscape',t:g,r:['-84px','0px','641px','400px','auto','auto'],f:[x3,im+g4,'0px','0px']},{id:'Rectangle',t:m,r:['213px','-15px','77px','441px','auto','auto'],o:0.5,f:[x5],s:[0,xc,i]},{id:'locatie',t:x,r:['0px','163px','213px','74px','auto','auto'],text:s6,align:"center",n:[x8,[x7,p],xc,l,i,"",x9,""]},{id:'temp',t:x,r:['215px','10px','auto','auto','auto','auto'],text:s10,align:"left",n:[x8,[x11,p],xc,x12,i,l,x9,x13]},{id:'cloudy',t:x,r:['0px','237px','213px','25px','auto','auto'],text:s14,align:"center",n:[x8,[x15,p],xc,x16,x17,l,x9,""]},{id:'min',t:x,r:['215px','76px','auto','auto','auto','auto'],text:s18,align:"center",n:[x8,[x15,p],xc,x16,x17,l,x9,x13]},{id:'max',t:x,r:['215px','111px','auto','auto','auto','auto'],text:s19,align:"center",n:[x8,[x15,p],xc,x16,x17,l,x9,x13]},{id:'minT',t:x,r:['266px','76px','auto','auto','auto','auto'],text:s20,align:"center",n:[x8,[x15,p],xc,x21,x17,l,x9,x13]},{id:'maxT',t:x,r:['266px','111px','auto','auto','auto','auto'],text:s22,align:"center",n:[x8,[x15,p],xc,x21,x17,l,x9,x13]},{id:'inputcontainer',t:m,r:['20px','355px','176px','25px','auto','auto'],o:0.49,f:[x23],s:[0,"rgb(0, 0, 0)",i]},{id:'rectangle',t:m,r:['0px','355px','20px','25px','auto','auto'],o:0.49,f:[x23],s:[0,"rgb(0, 0, 0)",i]},{id:'rectangleCopy',t:m,r:['196px','355px','17px','25px','auto','auto'],o:0.49,f:[x23],s:[0,"rgb(0, 0, 0)",i]},{id:'rectangleCopy2',t:m,r:['290px','355px','17px','25px','auto','auto'],o:0.49,f:[x23],s:[0,"rgb(0, 0, 0)",i]}],style:{'${Stage}':{isStage:true,r:['null','null','300px','400px','auto','auto'],overflow:'hidden',f:[x23]}}},tt:{d:0,a:y,data:[]}}};AdobeEdge.registerCompositionDefn(compId,symbols,fonts,scripts,resources,opts);})("EDGE-57309002");
(function($,Edge,compId){var Composition=Edge.Composition,Symbol=Edge.Symbol;var baseURL="https://query.yahooapis.com/v1/public/yql?q=";var woeidYQL="select * from geo.placefinder where text=";var weatherYQL="select * from weather.forecast where woeid="
function setup(){var mijnStage=Edge.getComposition(compId).getStage();var container=mijnStage.$("inputcontainer");var searchInput=$("<input/>").attr({'type':'input','id':'searchInput','value':''});searchInput.appendTo(container);searchInput.keyup(searchInputKeyUpHandler);}
function getWoeId(stad)
{$.getJSON(baseURL+woeidYQL+"'"+stad+"'&format=json",woeidHandler);}
function woeidHandler(data)
{getWeather(data.query.results.Result.woeid);}
function getWeather(id)
{$.getJSON(baseURL+weatherYQL+id+" and u='c'&format=json",weatherHandler);}
function weatherHandler(data)
{var temp=data.query.results.channel.item.condition.temp;var city=data.query.results.channel.location.city;var minT=data.query.results.channel.item.forecast[0].low;var maxT=data.query.results.channel.item.forecast[0].high;var condition=data.query.results.channel.item.condition.text;var mijnStage=Edge.getComposition(compId).getStage();mijnStage.$("temp").html(temp+"°");mijnStage.$("locatie").html(city);mijnStage.$("minT").html(minT+"°");mijnStage.$("maxT").html(maxT+"°");mijnStage.$("cloudy").html(condition);}
function searchInputKeyUpHandler(eventje){if(eventje.keyCode==13){console.log(eventje);getWoeId(eventje.target.value);}}
Edge.registerEventBinding(compId,function($){
//Edge symbol: 'stage'
(function(symbolName){Symbol.bindSymbolAction(compId,symbolName,"creationComplete",function(sym,e){setup();getWoeId("Kortrijk");});
//Edge binding end
})("stage");
//Edge symbol end:'stage'
})})(AdobeEdge.$,AdobeEdge,"EDGE-57309002");